name: absenkuy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  dropdown_button2: ^2.3.9
  syncfusion_flutter_charts: ^24.2.7+1
  flutter_native_splash: ^2.3.10
  cloud_firestore: ^4.14.0

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/icon/

flutter_native_splash:
  color: "#F96060"
  image: assets/images/logo.png
  android: true
  ios: true

